spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: >-
      jdbc:oracle:thin:@(DESCRIPTION=
        (ADDRESS_LIST=
          (ADDRESS=(PROTOCOL=TCP)(HOST=${DB_HOST})(PORT=${DB_PORT}))
          (ADDRESS=(PROTOCOL=TCP)(HOST=${STDB_HOST})(PORT=${DB_PORT}))
        )
        (CONNECT_DATA=(SERVICE_NAME=${DB_NAME}))
        (FAILOVER=on)(LOAD_BALANCE=off)
      )
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  application:
    name: store-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  # 읽기 전용 파일시스템 대비 설정
  servlet:
    multipart:
      location: /app/tmp  # 파일 업로드 임시 디렉토리

server:
  port: 8080
  shutdown: graceful
  tomcat:
    basedir: /app/tomcat  # Tomcat 기본 디렉토리
    accesslog:
      enabled: false  # 로그 파일 쓰기 방지

cloud:
  aws:
    region:
      static: ap-northeast-2
app:
  s3:
    bucket:
      name: ${S3_BUCKET_NAME}
    store-image:
      prefix: ${S3_IMAGE_PREFIX}

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE